SELECT * FROM PLACE;

INSERT INTO PLACE VALUES(PLACE_SEQ.NEXTVAL, '소강당', '서초 WALB 2층', 'place2.jpg');
INSERT INTO PLACE VALUES(PLACE_SEQ.NEXTVAL, '소회의실', '종로 WALB 4층', 'place3.jpg');
INSERT INTO PLACE VALUES(PLACE_SEQ.NEXTVAL, '대회의실', '종로 WALB 5층', 'place4.jpg');
INSERT INTO PLACE VALUES(PLACE_SEQ.NEXTVAL, '동아리실', '동대문 WALB 1층', 'place5.jpg');

DELETE FROM PLACE;

COMMIT;